# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-06 06:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_key', models.CharField(blank=True, max_length=254, null=True)),
                ('title', models.CharField(choices=[('mr', 'Mr'), ('mrs', 'Mrs'), ('ms', 'Ms'), ('miss', 'Miss')], max_length=254)),
                ('date_of_birth', models.DateField()),
                ('marital_status', models.CharField(choices=[('single', 'Single'), ('married', 'Married')], max_length=254)),
                ('sin', models.CharField(blank=True, max_length=9, null=True)),
                ('address', models.CharField(max_length=254)),
                ('city', models.CharField(max_length=254)),
                ('province', models.CharField(max_length=254)),
                ('postal_code', models.CharField(max_length=6)),
                ('residential_status', models.CharField(choices=[('own', 'Own'), ('rent', 'Rent'), ('lease', 'Lease')], max_length=254)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
