# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-07 00:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lemonaid', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='creditor_balance',
            field=models.FloatField(default=0),
        ),
    ]
