# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-06 06:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lemonaid', '0002_expenses'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Expenses',
            new_name='Flow',
        ),
    ]
