# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-06 06:59
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lemonaid', '0003_auto_20160206_0645'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('interest', models.FloatField()),
                ('duration', models.DurationField(default=datetime.timedelta(364))),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='creditor_balance',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lemonaid.UserProfile'),
        ),
    ]
